name: Release
on:
  push:
    branches:
      - dev
#env:
#  GLOBAL_ENV: globalenv
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set committer
        run: |
          git config user.name "Derek Li"
          git config user.email "lideyu888@163.com"
      - name: Install
        run: |
          yarn
      - name: Build Packages
        run: |
          yarn amap-js:build
      - name: Build the docs and deploy to git-pages
        run: |
          yarn docs:deploy
      - run: ls ${{ github.workspace }}
